//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsEvdTools.Gen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsEvdTools.Gen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     public class {2}Args
        ///    {{
        ///        {3}
        ///
        ///        internal {2}Args(BexReader br)
        ///        {{
        ///            {4}
        ///        }}
        ///    }}
        ///
        ///    public bool {2}(T action)
        ///        =&gt; Is(action, {0}, {1});
        ///
        ///    public bool {2}(T action, out {2}Args? args)
        ///        =&gt; ParseMaybe(action, {0}, {1}, br =&gt; new(br), out args);
        ///
        ///    public T {2}({5})
        ///        =&gt; CreateAction({0}, {1}, [{6}]);.
        /// </summary>
        internal static string EvdActionBuilderActionTemplate {
            get {
                return ResourceManager.GetString("EvdActionBuilderActionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Bex;
        ///
        ///namespace FsEvdTools;
        ///
        ///public class {0}&lt;T&gt; : EvdActionBuilder&lt;T&gt;
        ///{{
        ///    public {0}(ActionImporter importAction, ActionExporter exportAction) : base(importAction, exportAction) {{ }}
        ///        
        ///#pragma warning disable IDE1006 // Naming Styles
        ///{1}
        ///#pragma warning restore IDE1006 // Naming Styles
        ///}}
        ///.
        /// </summary>
        internal static string EvdActionBuilderTemplate {
            get {
                return ResourceManager.GetString("EvdActionBuilderTemplate", resourceCulture);
            }
        }
    }
}
